{{- range .Values.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ kebabcase .name }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ $.Values.controller.batch.containerName }}
            image: {{ $.Values.controller.batch.image }}:{{ $.Values.controller.batch.image.tag }}
            imagePullPolicy: Always
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env }}
            - name: JOB
              value: {{ .name }}
            envFrom:
            - secretRef:
                name: {{ $.Values.secret.name }}
          imagePullSecrets:
          - name: docker-secret
{{- end }}
