{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ kebabcase .name }}
spec:
  schedule: {{ .schedule }}
  timeZone: 'Asia/Seoul'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ $.Values.controller.batch.containerName }}
            image: {{ $.Values.controller.batch.image.name }}:{{ $.Values.controller.batch.image.tag }}
            imagePullPolicy: Always
            env:
            - name: JAVA_OPTS
              value: -Duser.timezone=Asia/Seoul
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env }}
            - name: JOB
              value: {{ .name }}
            envFrom:
            - secretRef:
                name: {{ $.Values.secret.name }}
          imagePullSecrets:
          - name: docker-secret
---
{{- end }}
