apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.mongodb.name }}
spec:
  serviceName: {{ .Values.service.mongodb.name }}
  replicas: {{ .Values.db.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.mongodb.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.mongodb.label }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:6.0.9-rc1
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: {{ .Values.db.mongodb.storage.name }}
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "app={{ .Values.db.mongodb.label }}"
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.db.mongodb.storage.name }}
    spec:
      accessModes:
        - {{ .Values.db.mongodb.storage.accessMode }}
      resources:
        requests:
          storage: {{ .Values.db.mongodb.storage.request }}
---
